### ISSUE TITLE
Testsuite error

### ISSUE THREAD

**Issue by aylen384** [dashohoxha/pw#23]
On Archlinux the Testsuite doesn't run through:

```
$ tests/t0401-find.t 
ok 1 - Create an archive.
ok 2 - Create some test entries.
ok 3 - Test usage
ok 4 - Test find
not ok 5 - Test find --tree
#	
#	    cat <<-"_EOF" > find-1.txt &&
#	Search Terms: test5
#	`-- test2
#	    `-- test5
#	_EOF
#	    pwp find test5 -t | remove_special_chars > find-2.txt &&
#	    test_cmp find-1.txt find-2.txt
#	
# failed 1 among 5 test(s)
1..5
```

```$ tests/t0401-find.t --verbose```
--> http://pastebin.f3l.de/5ac0c2eee3c62.txt

**Comment by dashohoxha** [comment]
Nice catch. If you try `pw --help` you will see that the command `find` has ho option `-t` or `--tree`. Maybe it had such an option in an earlier version, but it has been removed. So, the solution is to remove this test case, it is testing for a feature that does not exist (has been removed).
